server {
	listen 8080;
	server_name localhost;
	client_max_body_size 1M;

	error_page 404 test_site/errors/404.html;

	location / {
		root test_site;
		index index.html;
		autoindex on;
		methods GET POST DELETE;
	}

	location /upload {
		root test_site/upload;
		upload_store test_site/upload;
		methods GET POST DELETE;
		autoindex on;
	}

	location /cgi-bin {
		root test_site/cgi-bin;
		cgi_extension .py;
		cgi_path /usr/bin/python3;
		methods GET POST;
	}
}
