events {
	worker_connections 1024;
}

http {
	server {
		listen 8080;
		server_name localhost;
		client_max_body_size 200m;

		location / {
			root .;
			methods GET;
			autoindex on;
		}

		location /post_body {
			root .;
			methods POST;
			upload_store /tmp;
			client_max_body_size 100;
		}

		location /directory {
			root YoupiBanane;
			methods GET POST;
			index youpi.bad_extension;
			autoindex off;
			cgi_redir .bla ./cgi_tester;
		}
	}
}
